version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:15-alpine
    volumes:
      - postgresql15:/var/lib/postgresql/data
    env_file:
      - ./.env
  web_recipes:
    image: vabene1111/recipes
    restart: always
    #debug access via http://<server-ip>:8080
    #ports:
    # - 8080:8080
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    env_file:
      - ./.env
  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    # debug nginx
    #command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media
    labels: # traefik example labels
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.recipes.rule=Host(`recipes.${TRAEFIK_LE_CERT_WILDCARD_DOMAIN_NAME}`)"
      # access over entrypoint websecure
      - "traefik.http.routers.recipes.entrypoints=websecure"
      - "traefik.http.routers.recipes.tls=true"
      - "traefik.http.routers.recipes.tls.certresolver=myresolver"
    depends_on:
      - web_recipes
    env_file:
      - ./.env
    networks:
      - default
      - traefik_external

networks:
  default:
  traefik_external: # This is you external traefik network
    external: true
    name: traefik
volumes:
  nginx_config:
  staticfiles:
  postgresql15:
